# Generated by Django 4.2 on 2023-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=1, upload_to='main/articles/', verbose_name='Прикрепить статьи'),
            preserve_default=False,
        ),
    ]
