# Generated by Django 4.2 on 2023-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('category', models.CharField(choices=[('1', 'Педагогические науки'), ('2', 'Искусство и гуманитарные науки'), ('3', 'Социальные науки, журналистика и информация'), ('4', 'Бизнес, управление и право'), ('5', 'Естественные науки, математика и статистика'), ('6', 'Информационно-коммуникационные технологии'), ('7', 'Инженерные, обрабатывающие и строительные отрасли'), ('8', 'Сельское хозяйство и биоресурсы'), ('9', 'Ветеринария'), ('10', 'Здравоохранение'), ('11', 'Услуги'), ('12', 'Национальная безопасность и военное дело')], default='Педагогические науки', max_length=255, verbose_name='Научное направление')),
                ('file', models.FileField(upload_to='main/articles/', verbose_name='Прикрепить статьи')),
                ('date_created', models.DateField(verbose_name='Публикация выпуска')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
