# Generated by Django 4.2 on 2023-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_publisher_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='file',
            field=models.FileField(upload_to='main/publishers/', verbose_name='Прикрепить статьи'),
        ),
    ]
