# Generated by Django 4.2 on 2023-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_alter_article_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='staff',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
