# Generated by Django 4.2 on 2023-09-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_article_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='title',
        ),
    ]
