# Generated by Django 4.2 on 2023-09-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_publisher_poster_remove_publisher_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='main/posters/', verbose_name='Обложка'),
        ),
    ]
